#version: '3'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    networks:
      - odoo-net
    #volumes:
     # - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:15
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
    #command: odoo -i base
    networks:
      - odoo-net

networks:
  odoo-net:

volumes:
  odoo-db-data:
